In [17]:
import numpy as np

np.random.seed(42)

matrix1 = np.random.randint(1, 101, size=(4, 4))
print(matrix1)
print()

print(f'sum: {np.sum(matrix1)}')

print(f'min: {np.min(matrix1)}')
print(f'max: {np.max(matrix1)}')

matrix2 = matrix1.copy()
matrix2[matrix2 % 2 == 0] = 0

print(matrix2)

print(f'row sum: {matrix2.sum(axis=1)}')
print(f'col sum: {matrix2.sum(axis=0)}')

print(matrix2.transpose())

[[ 52  93  15  72]
 [ 61  21  83  87]
 [ 75  75  88 100]
 [ 24   3  22  53]]

sum: 924
min: 3
max: 100
[[ 0 93 15  0]
 [61 21 83 87]
 [75 75  0  0]
 [ 0  3  0 53]]
row sum: [108 252 150  56]
col sum: [136 192  98 140]
[[ 0 61 75  0]
 [93 21 75  3]
 [15 83  0  0]
 [ 0 87  0 53]]
